# SPDX-License-Identifier: GPL-2.0
#
# Makefile for tracepoint test
#

obj-$(CONFIG_TRACEPOINT_MMAP)	+= vendordommap_test/
obj-$(CONFIG_TRACEPOINT_MPROTECT_PKEY)	+= vendordomprotectpkey_test/
obj-$(CONFIG_TRACEPOINT_TEST)	+= tracepoint_test/
obj-$(CONFIG_TRACEPOINT_AML_EMMC_PARTITION)	+= vendoramlemmcpartition_test/
obj-$(CONFIG_TRACEPOINT_FAKE_BOOT_PARTITION)	+= vendorfakebootpartition_test/
